package com.palla;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MemberDetailsResponse implements Serializable {
	private Object DontContByEmail;
	private Object DateOfBirth;
	private Object Email;
	private Object EmpID;
	private Object FirstName;
	private Object Gender;
	private Object Height;
	private Object LastName;
	private Object SubscriptnID;
	private Object DeviceMemberID;
	private Object SubscriptnType;
	private Object RegNumber;
	private Object LastUpdatedTime;
	private Object MemberType;
	private Object ConsWeightGain;
	private Object CrntLifeTimeSta;
	private Object DontRecvCalls;
	private Object DontCnctPhone;
	private Object DontCnctSMS;
	private Object DontSendCard;
	private Object DontSendCoupon;
	private Object EnrollmentDate;
	private Object FeePaid;
	private Object LastAchvdMStone;
	private Object LastContactDate;
	private Object LastNteEntrDate;
	private Object LocationID;
	private Object LastLocationID;
	private Object MeetingDate;
	private Object MtngOccrID;
	private Object CouponCode;
	private Object ExpirationDate;
	private Object LastUsedDate;
	private Object ProductID;
	private Object NoWeeksAttended;
	private Object Phone1;
	private Object PhoneType1;
	private Object Phone2;
	private Object PhoneType2;
	private Object PrevLifeTimeSta;
	private Object ShippingAddr1;
	private Object ShippingAddr2;
	private Object ShippingCity;
	private Object ShippingCountry;
	private Object ShippingState;
	private Object ShippingZipCode;
	private Object StartDate;
	private Object MemberStatus;
	private Object TransactionType;
	private Object WeeksCompleted;
	private Object WeightGain;
	private Object RegStatus;
	private Object MemberID;
	private Object GoalWeight;
	private Object StartWeight;
	private Object RegDate;
	private Object IncompleteData;
	private Object PreRegNumber;
	private Object UniqueID;
	private Object UserStsEndPrd;
	private Object UserComments;
	private Object UserStsChngRsn;
	private Object SubscnMemberID;
	private Object EmailID;
	private Object EnterpriseID;
	private Object LinkType;
	private Object UserName;
	private Object LocalTime;
	private Object SessionNumber;
	private Object TrackerID;
	private Object MaintenanceMode;
	private Object TrackerStartDate;
	private Object FailedDate;
	private Object Eligible;
	private Object EligibleDate;
	private Object PaidLastFee;
	private Object WeightCountMet;
	private Object LastAttendanceDate;
	private Object NHSNumber;
	private Object DiabetesFlag;
	private Object DisabledFlag;
	private Object Vegetarian;
	private Object ThirdPartyID;
	private Object ReferralSource;
	private Object InsuranceCompanyName;
	private Object GPPractice;
	private Object Ethnicity;
	private Object EmpStatusID;
	private Object BreastFeedingFlag;
	private Object NickName;
	private Object IsReEnroll;
	private Object ChannelSource;
	private Object Phone3;
	private Object PhoneType3;
	private Object MeetingFeeId;
	private Object TotalSessionCount;
	private Object RemainingSessionCount;
	private Object WWSubscrType;
	private Object PersonalGoalWeight;
	private Object MPStatusCode;
	private Object MemberStatusExpDate;
	private Object PreviousLifeEndDate;
	private Object OptDate;
	private Object ProgrammeID;
	private Object StatusChangeID;


}
